from dataclasses import dataclass

UUID4_HEX_LENGTH = 32


@dataclass(frozen=True)
class Constants:
    GC_GRACE_PERIOD_SECONDS = 3600 * 24 * 10
    GC_OP_COUNT_MODULO_TRIGGER = 100
    CHECK_TARGETS_INTERVAL_SECONDS = 10
    GOSSIP_INTERVAL_SECONDS = 2
    VOTE_RESOLVE_INTERVAL_SECONDS = 10
    PROACTIVE_VOTER_INTERVAL_SECONDS = 2
    STATE_PATH = "storage/state.json"
    ID_PATH = "storage/.node_id"
    NODE_ID_PREFIX = "ng-node-"
    NODE_ID_LENGTH = len(NODE_ID_PREFIX) + UUID4_HEX_LENGTH
    CLUSTER_ID_PREFIX = "ng-cluster-"
    CLUSTER_ID_LENGTH = len(CLUSTER_ID_PREFIX) + UUID4_HEX_LENGTH
    UP_WINDOW_SIZE = 300 // CHECK_TARGETS_INTERVAL_SECONDS
    DOWN_WINDOW_SIZE = UP_WINDOW_SIZE // 6
    DOWN_FAILURE_RATE_THRESHOLD = 0.3
    UP_SUCCESS_RATE_THRESHOLD = 0.95
    MAX_CONCURRENT_TARGET_CHECKS = 5
    GOSSIP_WARMUP_TIME = 120
    SEND_ALERT_ONE_IX_DELAY = 60
    TARGET_DOWN_ALERT_MESSAGE = "❌ Target: {} fell at: {}\n\nBy node: {}"
    TARGET_UP_ALERT_MESSAGE = "✅ Target: {} up at: {}\n\nBy node: {}"


constants = Constants()
